
version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
    healthcheck:
      test: ["CMD", "mongo", "mongodb://root:root@mongodb:27017/admin"]
      interval: 5s
      timeout: 5s
      retries: 2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    container_name: exchatge_mongo
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
    container_name: exchatge_server
volumes:
  db:
